// <auto-generated />
namespace HMSPlus.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserRolesModifiedagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRolesModifiedagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091121347_User Roles Modified again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
